### PR TITLE
Update FromCanUtilsLog.py

### PR DESCRIPTION
**Pull request by mitchdetailed**
Allow Extended ID's to be compared in the SocketCAN log file format

### CODE REVIEW

**Comment by rusefillc** [comment]
@brent-stone poke :)

**Comment by brent-stone** [comment]
Sorry I missed it. I'll check when I get home. ~4 hours

**Comment by rusefillc** [comment]
@mitchdetailed you have a merge conflict between two of your PRs
one is now merged, are you available to update this PR?

**Comment by brent-stone** [comment]
Mitch, it looks like this REGEX is slightly less robust than the one from the other pull request. Quickly eyeballing both of them and both seem reasonable. Want to cancel this one and we keep the more explicit version?

**Comment by mitchdetailed** [comment]
I'll cancel my request, yes

**Comment by brent-stone** [comment]
Closed to maintain the more explicit REGEX from the earlier pull request. Thanks to all the contributors.

**Pull request closed without merging**
